# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Leonardo Santoro
description: >- # this means to ignore newlines until "baseurl:"
  Leonardo Santoro
#baseurl: "/tree/master" # the subpath of the site
#url: "https://leonardoVsantoro.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile_picture.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: about
      slug: /
    - name: research
    - name: cv

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: leonardo.santoro@epfl.ch
      link: mailto:leonardo.santoro@epfl.ch
    - name: Location
      value: Department of Mathematics EPFL, CH-1015 Lausanne (CH)
      link: https://www.google.com/maps/dir//Department+of+Mathematics,+EPFL+FSB+SMA,+Station+8,+1015+Lausanne,+Svizzera/@46.5201731,6.5266562,13z/data=!3m1!4b1!4m9!4m8!1m0!1m5!1m1!1s0x478c30fe0fe92fe5:0x98b5622112a251fd!2m2!1d6.5678555!2d46.5201805!3e3
      
  #  - name: WeChat
  #    value: YourWeChatUsername
  #    link: "#"
  follow:
    #- name: Twitter
    #  link: http://twitter.com/YourTwitterUsername
    #  username: "@YourTwitterUsername"
   # - name: Facebook
   #   link: http://facebook.com/YourFacebookUsername
    - name: LinkedIn
      link: https://www.linkedin.com/in/leonardo-santoro-abab15203/
    - name: GitHub
      link: https://github.com/leonardoVsantoro
   # - name: Dribbble
   #   link: https://dribbble.com/YourDribbbleUsername
   # - name: Weibo
   #   link: http://weibo.com/u/YourWeiboUsername
   # - name: RSS
   #   link: /feed.xml
    - name: ResearchGate
      link: https://www.researchgate.net/profile/Leonardo-Santoro-2
    - name: GoogleScholar
      link: https://scholar.google.com/citations?user=1PB3OkEAAAAJ&hl=it&oi=sra


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1




